[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false

# Hedera Testnet
[rpc_endpoints]
hedera_testnet = "https://testnet.hashio.io/api"
hedera_mainnet = "https://mainnet.hashio.io/api"
local = "http://localhost:8545"

[etherscan]
hedera_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://server-verify.hashscan.io" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
